#!/bin/bash
echo "=== Gallery Image Count by Category ==="
echo ""
echo "Arches (general):"
sed -n '/<!-- Arches -->/,/<!-- Columns/p' index.html | grep -c "gallery-item-category.*Arches"
echo ""
echo "Specialty Arch:"
sed -n '/<!-- Arches - Specialty Arch -->/,/<!-- Chiara Arch/p' index.html | grep -c "gallery-item-category.*Specialty Arch"
echo ""
echo "Chiara Arch:"
sed -n '/<!-- Chiara Arch -->/,/<!-- Walls/p' index.html | grep -c "gallery-item-category.*Chiara Arch"
echo ""
echo "Walls:"
sed -n '/<!-- Walls -->/,/<!-- Centerpieces/p' index.html | grep -c "gallery-item-category.*Walls"
echo ""
echo "Centerpieces:"
sed -n '/<!-- Centerpieces -->/,/<!-- Events/p' index.html | grep -c "gallery-item-category.*Centerpieces"
echo ""
echo "Full Event:"
sed -n '/<!-- Events -->/,/<\/div>/p' index.html | grep -c "gallery-item-category.*Full Event"
